name: Auto Update KAI Data

on:
  schedule:
    # Runs every day at 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update station data
      run: |
        python -c "
        import requests
        import json
        from datetime import datetime
        
        # Fetch fresh station data
        try:
            response = requests.get('https://api-partner.kai.id/api/stations2', timeout=30)
            if response.status_code == 200:
                stations = response.json()
                
                # Save to data file
                with open('data/stations.json', 'w', encoding='utf-8') as f:
                    json.dump(stations, f, ensure_ascii=False, indent=2)
                    
                print(f'✅ Updated {len(stations)} stations at {datetime.now()}')
            else:
                print(f'❌ Failed to fetch stations: {response.status_code}')
        except Exception as e:
            print(f'❌ Error updating stations: {e}')
        "
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "🤖 Auto-update KAI data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Vercel deployment
      run: |
        echo "✅ Data updated successfully!"
        echo "🚀 Vercel will auto-deploy the changes"
